"""Load SDIM metadata CSVs and look up internal codes by human-readable names.

The CSVs are generated by ``scripts/build_metadata.py`` and contain the
mappings needed to build a :class:`~sdim.query.Query` without hand-writing
internal codes (e.g. river ``200``, variable kind ``0002``).
"""

from __future__ import annotations

import os
import unicodedata
from pathlib import Path

import pandas as pd

_META_DIR = os.environ.get(
    "SDIM_METADATA_DIR",
    str(Path(__file__).resolve().parent.parent / "metadata"),
)

# CSV file -> (default flavor label, code column)
_FLAVORS = {
    "networks": ("network", "code"),
    "subnetworks": ("subnetwork", "code"),
    "variables": ("variable", None),  # composite: g/f/v
    "rivers": ("river", "code"),
    "basins": ("basin", "code"),
    "comarcas": ("comarca", "code"),
    "municipis": ("municipi", "code"),
    "aquifers": ("aquifer", "code"),
    "masses": ("mass", "code"),
    "reservoirs": ("reservoir", "code"),
    "stations": ("station", "station"),
    "targets": ("target", "id"),
    "station_variables": ("station-variable", "variable_id"),
}


def _norm(text: str) -> str:
    return unicodedata.normalize("NFD", text).encode("ascii", "ignore").decode().lower()


class Catalog:
    """Lazy access to the SDIM metadata tables."""

    def __init__(self, meta_dir: str | Path | None = None):
        self.meta_dir = Path(meta_dir) if meta_dir else Path(_META_DIR)
        self._tables: dict[str, pd.DataFrame] = {}

    def _load(self, flavor: str) -> pd.DataFrame:
        if flavor in self._tables:
            return self._tables[flavor]
        path = self.meta_dir / f"{flavor}.csv"
        if not path.exists():
            raise FileNotFoundError(
                f"metadata table not found: {path}. Run scripts/build_metadata.py first."
            )
        df = pd.read_csv(path, dtype=str, keep_default_na=False)
        self._tables[flavor] = df
        return df

    def table(self, flavor: str) -> pd.DataFrame:
        return self._load(flavor)

    # -- generic search ----------------------------------------------------

    def search(self, flavor: str, term: str, *, period: str | None = None) -> pd.DataFrame:
        """Return rows of ``flavor`` whose name contains ``term``.

        Matching is case- and accent-insensitive and covers ``name`` as well as
        tiered names (``g_name``/``f_name``/``v_name`` for variables). If
        ``period`` is given, rows are filtered to that period.
        """
        df = self._load(flavor)
        q = _norm(term)
        name_cols = [c for c in
                     ("name", "g_name", "f_name", "v_name", "network_name",
                      "subnetwork_name", "category", "station_name")
                     if c in df.columns]
        if not name_cols:
            return df.iloc[0:0].copy()
        blob = df[name_cols].astype(str).apply(lambda r: " ".join(r), axis=1)
        mask = blob.map(_norm).str.find(q) >= 0
        out = df[mask].copy()
        if period is not None and "period" in out.columns:
            out = out[out["period"] == period]
        return out.reset_index(drop=True)

    # -- handy shortcuts ---------------------------------------------------

    def search_variables(self, term: str, *, period: str | None = None) -> pd.DataFrame:
        return self.search("variables", term, period=period)

    def variables_for(self, network: str, subnetwork: str, *, period: str = "after_2007") -> pd.DataFrame:
        df = self._load("variables")
        return df[(df.period == period)
                  & (df.network == network.zfill(4))
                  & (df.subnetwork == subnetwork.zfill(4))].reset_index(drop=True)

    # -- targets -----------------------------------------------------------

    def targets(self, period: str | None = None) -> pd.DataFrame:
        """The targets inventory: one row per (period, network, subnetwork)."""
        df = self._load("targets")
        if period is not None:
            df = df[df.period == period]
        return df.reset_index(drop=True)

    def target(self, target_id: str):
        """Return the targets.csv row for ``period:network:subnetwork``."""
        df = self._load("targets")
        hit = df[df.id == target_id]
        return hit.iloc[0] if len(hit) else None

    def target_station_variables(self, target_id: str) -> pd.DataFrame:
        """Per-target station↔variable-series table.

        ``target_id`` is ``"period:network:subnetwork"`` and the result has one
        row per (station, variable series).
        """
        period, network, subnetwork = target_id.split(":")
        path = self.meta_dir / "station_variables" / f"{period}_{network}_{subnetwork}.csv"
        if not path.exists():
            return pd.DataFrame()
        return pd.read_csv(path, dtype=str)

    def station_variables(self, term: str | None = None) -> pd.DataFrame:
        """The merged station↔variable table (optionally filtered by a name)."""
        df = self._load("station_variables")
        if term:
            q = _norm(term)
            mask = df.apply(
                lambda r: _norm(str(r.get("station_name", ""))).find(q) >= 0
                or _norm(str(r.get("variable_name", ""))).find(q) >= 0,
                axis=1,
            )
            df = df[mask]
        return df.reset_index(drop=True)

    def rivers(self, term: str | None = None, *, period: str | None = None) -> pd.DataFrame:
        df = self._load("rivers")
        if term:
            return self.search("rivers", term, period=period)
        return df

    def station_codes(self, term: str | None = None) -> list[str]:
        df = self._load("stations")
        if term:
            df = df[df.apply(lambda r: _norm(str(r.get("name", ""))).find(_norm(term)) >= 0, axis=1)]
        return df["station"].unique().tolist()

    def close(self) -> None:
        self._tables.clear()